FROM node:20-alpine AS builder

WORKDIR /app

RUN apk add --no-cache tzdata
ENV TZ=Africa/Nairobi

COPY package*.json ./
RUN npm ci --legacy-peer-deps --only=production

COPY . .
RUN npm run build

FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache tzdata
ENV TZ=Africa/Nairobi

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

EXPOSE 3002

CMD ["node", "dist/main"]
