export interface DashboardTheme {
  id: string;
  sidebar: string;
  sidebarBg: string;
  sidebarBorder: string;
  sidebarHover: string;
  sidebarActiveBg: string;
  sidebarActiveText: string;
  sidebarActiveBorder: string;
  sidebarIcon: string;
  sidebarText: string;
  sidebarUserBg: string;
  brand: string;
  brandText: string;
  brandSubtitle: string;
  navBg: string;
  navText: string;
  navHover: string;
  navActiveBg: string;
  navActiveText: string;
  navActiveBorder: string;
  navIcon: string;
  accent: string;
  accentHover: string;
  primary: string;
  primaryBg: string;
  primaryLight: string;
  primaryText: string;
  primaryBorder: string;
  primaryHover: string;
  gradientFrom: string;
  gradientTo: string;
  gradient: string;
  avatarBg: string;
  avatarText: string;
  headerBg: string;
  headerBorder: string;
  headerText: string;
  headerMuted: string;
  mainBg: string;
  mainContainer: string;
  cardBg: string;
  cardBorder: string;
  cardText: string;
  mutedText: string;
  dangerText: string;
  dangerBg: string;
  dangerHover: string;
  successText: string;
  successBg: string;
  notificationBg: string;
  toggleBtn: string;
  toggleBtnBg: string;
  collapsedWidth: string;
  expandedWidth: string;
}

export const THEMES: Record<string, DashboardTheme> = {
  student: {
    id: 'student',
    sidebar: 'bg-white',
    sidebarBg: 'bg-white border-r border-slate-200',
    sidebarBorder: 'border-slate-200',
    sidebarHover: 'hover:bg-primary-50',
    sidebarActiveBg: 'bg-primary-50',
    sidebarActiveText: 'text-primary-700',
    sidebarActiveBorder: 'border-l-4 border-primary',
    sidebarIcon: 'text-primary',
    sidebarText: 'text-slate-700',
    sidebarUserBg: 'bg-primary-100',
    brand: 'from-primary to-primary-400',
    brandText: 'text-slate-900',
    brandSubtitle: 'text-slate-500',
    navBg: 'bg-white',
    navText: 'text-slate-600',
    navHover: 'hover:bg-primary-50 hover:text-primary-700',
    navActiveBg: 'bg-primary-50',
    navActiveText: 'text-primary-700',
    navActiveBorder: 'border-l-4 border-primary',
    navIcon: 'text-primary',
    accent: 'bg-primary',
    accentHover: 'hover:bg-primary-600',
    primary: '#006a34',
    primaryBg: 'bg-primary',
    primaryLight: 'bg-primary-50',
    primaryText: 'text-primary-700',
    primaryBorder: 'border-primary-200',
    primaryHover: 'hover:bg-primary-50',
    gradientFrom: 'from-primary',
    gradientTo: 'to-primary-400',
    gradient: 'bg-gradient-to-br from-primary to-primary-400',
    avatarBg: 'bg-primary-100',
    avatarText: 'text-primary-700',
    headerBg: 'bg-white border-b border-slate-200',
    headerBorder: 'border-slate-200',
    headerText: 'text-slate-900',
    headerMuted: 'text-slate-500',
    mainBg: 'bg-slate-50',
    mainContainer: 'bg-slate-50/50',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-200',
    cardText: 'text-slate-900',
    mutedText: 'text-slate-500',
    dangerText: 'text-red-600',
    dangerBg: 'bg-red-50',
    dangerHover: 'hover:bg-red-50',
    successText: 'text-green-600',
    successBg: 'bg-green-50',
    notificationBg: 'bg-primary-50',
    toggleBtn: 'text-primary',
    toggleBtnBg: 'bg-white border border-slate-200',
    collapsedWidth: 'w-16',
    expandedWidth: 'w-64',
  },

  candidate: {
    id: 'candidate',
    sidebar: 'bg-white',
    sidebarBg: 'bg-white border-r border-amber-200',
    sidebarBorder: 'border-amber-200',
    sidebarHover: 'hover:bg-amber-50',
    sidebarActiveBg: 'bg-amber-50',
    sidebarActiveText: 'text-amber-700',
    sidebarActiveBorder: 'border-l-4 border-amber-500',
    sidebarIcon: 'text-amber-600',
    sidebarText: 'text-amber-900',
    sidebarUserBg: 'bg-amber-100',
    brand: 'from-amber-600 to-orange-600',
    brandText: 'text-amber-900',
    brandSubtitle: 'text-amber-700',
    navBg: 'bg-white',
    navText: 'text-amber-800',
    navHover: 'hover:bg-amber-50 hover:text-amber-700',
    navActiveBg: 'bg-amber-50',
    navActiveText: 'text-amber-700',
    navActiveBorder: 'border-l-4 border-amber-500',
    navIcon: 'text-amber-600',
    accent: 'bg-amber',
    accentHover: 'hover:bg-amber-600',
    primary: '#d97706',
    primaryBg: 'bg-amber',
    primaryLight: 'bg-amber-50',
    primaryText: 'text-amber-700',
    primaryBorder: 'border-amber-200',
    primaryHover: 'hover:bg-amber-50',
    gradientFrom: 'from-amber-600',
    gradientTo: 'to-orange-600',
    gradient: 'bg-gradient-to-br from-amber-600 to-orange-600',
    avatarBg: 'bg-amber-100',
    avatarText: 'text-amber-700',
    headerBg: 'bg-white border-b border-amber-200',
    headerBorder: 'border-amber-200',
    headerText: 'text-amber-900',
    headerMuted: 'text-amber-700',
    mainBg: 'bg-amber-50/30',
    mainContainer: 'bg-amber-50/20',
    cardBg: 'bg-white',
    cardBorder: 'border-amber-200',
    cardText: 'text-amber-900',
    mutedText: 'text-amber-600',
    dangerText: 'text-red-600',
    dangerBg: 'bg-red-50',
    dangerHover: 'hover:bg-red-50',
    successText: 'text-green-600',
    successBg: 'bg-green-50',
    notificationBg: 'bg-amber-50',
    toggleBtn: 'text-amber-600',
    toggleBtnBg: 'bg-white border border-amber-200',
    collapsedWidth: 'w-16',
    expandedWidth: 'w-64',
  },

  parent: {
    id: 'parent',
    sidebar: 'bg-white',
    sidebarBg: 'bg-white border-r border-blue-200',
    sidebarBorder: 'border-blue-200',
    sidebarHover: 'hover:bg-blue-50',
    sidebarActiveBg: 'bg-blue-50',
    sidebarActiveText: 'text-blue-700',
    sidebarActiveBorder: 'border-l-4 border-blue-500',
    sidebarIcon: 'text-blue-600',
    sidebarText: 'text-blue-900',
    sidebarUserBg: 'bg-blue-100',
    brand: 'from-blue-600 to-indigo-600',
    brandText: 'text-blue-900',
    brandSubtitle: 'text-blue-700',
    navBg: 'bg-white',
    navText: 'text-blue-800',
    navHover: 'hover:bg-blue-50 hover:text-blue-700',
    navActiveBg: 'bg-blue-50',
    navActiveText: 'text-blue-700',
    navActiveBorder: 'border-l-4 border-blue-500',
    navIcon: 'text-blue-600',
    accent: 'bg-blue',
    accentHover: 'hover:bg-blue-600',
    primary: '#2563eb',
    primaryBg: 'bg-blue',
    primaryLight: 'bg-blue-50',
    primaryText: 'text-blue-700',
    primaryBorder: 'border-blue-200',
    primaryHover: 'hover:bg-blue-50',
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-indigo-600',
    gradient: 'bg-gradient-to-br from-blue-600 to-indigo-600',
    avatarBg: 'bg-blue-100',
    avatarText: 'text-blue-700',
    headerBg: 'bg-white border-b border-blue-200',
    headerBorder: 'border-blue-200',
    headerText: 'text-blue-900',
    headerMuted: 'text-blue-600',
    mainBg: 'bg-blue-50/30',
    mainContainer: 'bg-blue-50/20',
    cardBg: 'bg-white',
    cardBorder: 'border-blue-200',
    cardText: 'text-blue-900',
    mutedText: 'text-blue-600',
    dangerText: 'text-red-600',
    dangerBg: 'bg-red-50',
    dangerHover: 'hover:bg-red-50',
    successText: 'text-green-600',
    successBg: 'bg-green-50',
    notificationBg: 'bg-blue-50',
    toggleBtn: 'text-blue-600',
    toggleBtnBg: 'bg-white border border-blue-200',
    collapsedWidth: 'w-16',
    expandedWidth: 'w-64',
  },

  teacher: {
    id: 'teacher',
    sidebar: 'bg-white',
    sidebarBg: 'bg-white border-r border-indigo-200',
    sidebarBorder: 'border-indigo-200',
    sidebarHover: 'hover:bg-indigo-50',
    sidebarActiveBg: 'bg-indigo-50',
    sidebarActiveText: 'text-indigo-700',
    sidebarActiveBorder: 'border-l-4 border-indigo-500',
    sidebarIcon: 'text-indigo-600',
    sidebarText: 'text-indigo-900',
    sidebarUserBg: 'bg-indigo-100',
    brand: 'from-indigo-600 to-purple-600',
    brandText: 'text-indigo-900',
    brandSubtitle: 'text-indigo-700',
    navBg: 'bg-white',
    navText: 'text-indigo-800',
    navHover: 'hover:bg-indigo-50 hover:text-indigo-700',
    navActiveBg: 'bg-indigo-50',
    navActiveText: 'text-indigo-700',
    navActiveBorder: 'border-l-4 border-indigo-500',
    navIcon: 'text-indigo-600',
    accent: 'bg-indigo',
    accentHover: 'hover:bg-indigo-600',
    primary: '#4f46e5',
    primaryBg: 'bg-indigo',
    primaryLight: 'bg-indigo-50',
    primaryText: 'text-indigo-700',
    primaryBorder: 'border-indigo-200',
    primaryHover: 'hover:bg-indigo-50',
    gradientFrom: 'from-indigo-600',
    gradientTo: 'to-purple-600',
    gradient: 'bg-gradient-to-br from-indigo-600 to-purple-600',
    avatarBg: 'bg-indigo-100',
    avatarText: 'text-indigo-700',
    headerBg: 'bg-white border-b border-indigo-200',
    headerBorder: 'border-indigo-200',
    headerText: 'text-indigo-900',
    headerMuted: 'text-indigo-600',
    mainBg: 'bg-indigo-50/30',
    mainContainer: 'bg-indigo-50/20',
    cardBg: 'bg-white',
    cardBorder: 'border-indigo-200',
    cardText: 'text-indigo-900',
    mutedText: 'text-indigo-600',
    dangerText: 'text-red-600',
    dangerBg: 'bg-red-50',
    dangerHover: 'hover:bg-red-50',
    successText: 'text-green-600',
    successBg: 'bg-green-50',
    notificationBg: 'bg-indigo-50',
    toggleBtn: 'text-indigo-600',
    toggleBtnBg: 'bg-white border border-indigo-200',
    collapsedWidth: 'w-16',
    expandedWidth: 'w-64',
  },

  tutor: {
    id: 'tutor',
    sidebar: 'bg-white',
    sidebarBg: 'bg-white border-r border-indigo-200',
    sidebarBorder: 'border-indigo-200',
    sidebarHover: 'hover:bg-indigo-50',
    sidebarActiveBg: 'bg-indigo-50',
    sidebarActiveText: 'text-indigo-700',
    sidebarActiveBorder: 'border-l-4 border-indigo-500',
    sidebarIcon: 'text-indigo-600',
    sidebarText: 'text-indigo-900',
    sidebarUserBg: 'bg-indigo-100',
    brand: 'from-indigo-600 to-purple-600',
    brandText: 'text-indigo-900',
    brandSubtitle: 'text-indigo-700',
    navBg: 'bg-white',
    navText: 'text-indigo-800',
    navHover: 'hover:bg-indigo-50 hover:text-indigo-700',
    navActiveBg: 'bg-indigo-50',
    navActiveText: 'text-indigo-700',
    navActiveBorder: 'border-l-4 border-indigo-500',
    navIcon: 'text-indigo-600',
    accent: 'bg-indigo',
    accentHover: 'hover:bg-indigo-600',
    primary: '#4f46e5',
    primaryBg: 'bg-indigo',
    primaryLight: 'bg-indigo-50',
    primaryText: 'text-indigo-700',
    primaryBorder: 'border-indigo-200',
    primaryHover: 'hover:bg-indigo-50',
    gradientFrom: 'from-indigo-600',
    gradientTo: 'to-purple-600',
    gradient: 'bg-gradient-to-br from-indigo-600 to-purple-600',
    avatarBg: 'bg-indigo-100',
    avatarText: 'text-indigo-700',
    headerBg: 'bg-white border-b border-indigo-200',
    headerBorder: 'border-indigo-200',
    headerText: 'text-indigo-900',
    headerMuted: 'text-indigo-600',
    mainBg: 'bg-indigo-50/30',
    mainContainer: 'bg-indigo-50/20',
    cardBg: 'bg-white',
    cardBorder: 'border-indigo-200',
    cardText: 'text-indigo-900',
    mutedText: 'text-indigo-600',
    dangerText: 'text-red-600',
    dangerBg: 'bg-red-50',
    dangerHover: 'hover:bg-red-50',
    successText: 'text-green-600',
    successBg: 'bg-green-50',
    notificationBg: 'bg-indigo-50',
    toggleBtn: 'text-indigo-600',
    toggleBtnBg: 'bg-white border border-indigo-200',
    collapsedWidth: 'w-16',
    expandedWidth: 'w-64',
  },

  super_admin: {
    id: 'super_admin',
    sidebar: 'bg-[#0f1729]',
    sidebarBg: 'bg-[#0f1729] border-r border-[#2a3a5c]',
    sidebarBorder: 'border-[#2a3a5c]',
    sidebarHover: 'hover:bg-[#1a2540]',
    sidebarActiveBg: 'bg-[#1a2540]',
    sidebarActiveText: 'text-amber-300',
    sidebarActiveBorder: 'border-l-4 border-amber-400',
    sidebarIcon: 'text-amber-400',
    sidebarText: 'text-[#dae2fd]',
    sidebarUserBg: 'bg-amber-900/30',
    brand: 'from-amber-500 to-amber-600',
    brandText: 'text-amber-300',
    brandSubtitle: 'text-amber-400/70',
    navBg: 'bg-[#0f1729]',
    navText: 'text-[#becabd]',
    navHover: 'hover:bg-[#1a2540] hover:text-amber-300',
    navActiveBg: 'bg-[#1a2540]',
    navActiveText: 'text-amber-300',
    navActiveBorder: 'border-l-4 border-amber-400',
    navIcon: 'text-amber-400',
    accent: 'bg-amber',
    accentHover: 'hover:bg-amber-600',
    primary: '#d97706',
    primaryBg: 'bg-amber',
    primaryLight: 'bg-amber-900/20',
    primaryText: 'text-amber-300',
    primaryBorder: 'border-amber-700',
    primaryHover: 'hover:bg-amber-900/30',
    gradientFrom: 'from-amber-500',
    gradientTo: 'to-amber-600',
    gradient: 'bg-gradient-to-br from-amber-500 to-amber-600',
    avatarBg: 'bg-[#1a2540]',
    avatarText: 'text-amber-300',
    headerBg: 'bg-[#131b2e] border-b border-[#2a3a5c]',
    headerBorder: 'border-[#2a3a5c]',
    headerText: 'text-[#dae2fd]',
    headerMuted: 'text-[#becabd]',
    mainBg: 'bg-[#0b1326]',
    mainContainer: 'bg-[#0b1326]',
    cardBg: 'bg-[#171f33]',
    cardBorder: 'border-[#3f4940]',
    cardText: 'text-[#dae2fd]',
    mutedText: 'text-[#becabd]',
    dangerText: 'text-[#ffb4ab]',
    dangerBg: 'bg-[#93000a]/20',
    dangerHover: 'hover:bg-[#93000a]/20',
    successText: 'text-[#7eda95]',
    successBg: 'bg-[#7eda95]/10',
    notificationBg: 'bg-amber-900/20',
    toggleBtn: 'text-amber-400',
    toggleBtnBg: 'bg-[#1a2540] border border-[#2a3a5c]',
    collapsedWidth: 'w-16',
    expandedWidth: 'w-64',
  },

  institution_admin: {
    id: 'institution_admin',
    sidebar: 'bg-[#0f1729]',
    sidebarBg: 'bg-[#0f1729] border-r border-[#2a3a5c]',
    sidebarBorder: 'border-[#2a3a5c]',
    sidebarHover: 'hover:bg-[#1a2540]',
    sidebarActiveBg: 'bg-[#1a2540]',
    sidebarActiveText: 'text-[#7eda95]',
    sidebarActiveBorder: 'border-l-4 border-[#47a263]',
    sidebarIcon: 'text-[#7eda95]',
    sidebarText: 'text-[#dae2fd]',
    sidebarUserBg: 'bg-[#47a263]/20',
    brand: 'from-[#47a263] to-[#7eda95]',
    brandText: 'text-[#7eda95]',
    brandSubtitle: 'text-[#b7c8e1]',
    navBg: 'bg-[#0f1729]',
    navText: 'text-[#becabd]',
    navHover: 'hover:bg-[#1a2540] hover:text-[#7eda95]',
    navActiveBg: 'bg-[#1a2540]',
    navActiveText: 'text-[#7eda95]',
    navActiveBorder: 'border-l-4 border-[#47a263]',
    navIcon: 'text-[#7eda95]',
    accent: 'bg-[#47a263]',
    accentHover: 'hover:bg-[#47a263]/80',
    primary: '#006a34',
    primaryBg: 'bg-[#47a263]',
    primaryLight: 'bg-[#47a263]/10',
    primaryText: 'text-[#7eda95]',
    primaryBorder: 'border-[#47a263]',
    primaryHover: 'hover:bg-[#47a263]/20',
    gradientFrom: 'from-[#47a263]',
    gradientTo: 'to-[#7eda95]',
    gradient: 'bg-gradient-to-br from-[#47a263] to-[#7eda95]',
    avatarBg: 'bg-[#1a2540]',
    avatarText: 'text-[#7eda95]',
    headerBg: 'bg-[#131b2e] border-b border-[#2a3a5c]',
    headerBorder: 'border-[#2a3a5c]',
    headerText: 'text-[#dae2fd]',
    headerMuted: 'text-[#becabd]',
    mainBg: 'bg-[#0b1326]',
    mainContainer: 'bg-[#0b1326]',
    cardBg: 'bg-[#171f33]',
    cardBorder: 'border-[#3f4940]',
    cardText: 'text-[#dae2fd]',
    mutedText: 'text-[#becabd]',
    dangerText: 'text-[#ffb4ab]',
    dangerBg: 'bg-[#93000a]/20',
    dangerHover: 'hover:bg-[#93000a]/20',
    successText: 'text-[#7eda95]',
    successBg: 'bg-[#7eda95]/10',
    notificationBg: 'bg-[#47a263]/10',
    toggleBtn: 'text-[#7eda95]',
    toggleBtnBg: 'bg-[#1a2540] border border-[#2a3a5c]',
    collapsedWidth: 'w-16',
    expandedWidth: 'w-64',
  },
};

export function getTheme(role: string, isCandidate: boolean): DashboardTheme {
  if (role === 'student' && isCandidate) return THEMES.candidate;
  if (role === 'super_admin') return THEMES.super_admin;
  if (role === 'institution_admin') return THEMES.institution_admin;
  if (role === 'parent') return THEMES.parent;
  if (role === 'teacher') return THEMES.teacher;
  if (role === 'tutor') return THEMES.tutor;
  return THEMES.student;
}
